## Utilitaries and imports

In [15]:
import pandas as pd
import numpy as np
import csv

In [2]:
def build_df(i):
    df = pd.read_csv("training_records/episodes/ep"+str(i)+".csv")
    df = df[df["kind"] == "AV"]
    df = df.sort_values(by="start_time").reset_index(drop=True)
    df["reward"] = -1*df["travel_time"]
    df = df[["reward","action"]]
    return df

def write_line(i,df):
    line = str(i)
    for i in range(10):
        line = line + "," + str(df["reward"].values[i])
    return line

def id_to_strategy(id):
    strategy = [0 for _ in range(10)]
    i = 0
    while id > 0:
        if id % 2 == 1:
            strategy[9-i] = 1
        id = id//2
        i += 1
    return strategy


def strategy_to_id(s):
    id = 0
    for i in range(10):
        id += s[i]*(2**(9-i))
    return id

## Build dataframe from last experiment

In [ ]:
tl_0 = 10
tl_1 = 50-tl_0
file_name = "reward_df_50agents_"+str(tl_0)+"_"+str(tl_1)+".csv"
file_name

'reward_df_50agents_30_20.csv'

In [12]:
with open(file_name, "w") as f:
    f.write("id,0,1,2,3,4,5,6,7,8,9\n")
    for i in range(1024):
        data = build_df(i+1)
        text = write_line(i,data)
        f.write(text+"\n")

In [7]:
df_reward = pd.read_csv(file_name)
df_reward

,id,0,1,2,3,4,5,6,7,8,9
0,0,-0.616667,-0.716667,-0.783333,-0.80,-1.150000,-1.15,-1.250000,-1.183333,-1.216667,-1.200000
1,1,-0.616667,-0.716667,-0.783333,-0.80,-1.150000,-1.15,-1.250000,-1.183333,-1.216667,-1.600000
2,2,-0.616667,-0.716667,-0.783333,-0.80,-1.150000,-1.15,-1.250000,-1.183333,-1.716667,-1.166667
3,3,-0.616667,-0.716667,-0.783333,-0.80,-1.150000,-1.15,-1.250000,-1.183333,-1.700000,-1.666667
4,4,-0.616667,-0.716667,-0.783333,-0.80,-1.150000,-1.15,-1.250000,-1.750000,-1.183333,-1.183333
...,...,...,...,...,...,...,...,...,...,...,...
1019,1019,-1.050000,-2.000000,-2.016667,-2.95,-2.966667,-3.90,-3.933333,-1.100000,-4.716667,-4.666667
1020,1020,-1.050000,-1.983333,-2.016667,-2.95,-2.966667,-3.90,-3.933333,-4.766667,-1.100000,-1.150000
1021,1021,-1.050000,-2.000000,-2.016667,-2.95,-2.966667,-3.90,-3.933333,-4.766667,-1.100000,-4.666667
1022,1022,-1.050000,-2.000000,-2.016667,-2.95,-2.966667,-3.90,-3.933333,-4.766667,-4.766667,-1.150000
1023,1023,-1.050000,-1.983333,-2.016667,-2.95,-2.966667,-3.90,-3.933333,-4.783333,-4.766667,-5.616667

In [8]:
tab_reward = [[] for _ in range(10)]
for i in range(10):
    tab_reward[i] = df_reward[str(i)].values

tab_reward[0]

array([-0.61666667, -0.61666667, -0.61666667, ..., -1.05      ,
       -1.05      , -1.05      ], shape=(1024,))

## Build composite dataframe

In [8]:
list_tl = [10,13,15,16,19,20,22,25,28,30,31,34,35,37,40]
list_tl_inv = [list_tl[-(i+1)] for i in range(len(list_tl))]
list_tl, list_tl_inv

([10, 13, 15, 16, 19, 20, 22, 25, 28, 30, 31, 34, 35, 37, 40],
 [40, 37, 35, 34, 31, 30, 28, 25, 22, 20, 19, 16, 15, 13, 10])

In [ ]:
tl_0 = 37
tl_1 = 50-tl_0
file_name = "reward_df_test_"+str(tl_0)+"_"+str(tl_1)+".csv"
print("tl_0 = %s, tl_1 = %s" % (tl_0,tl_1))
df_reward = pd.read_csv(file_name)
df_reward

37 13
tl_0 = 37, tl_1 = 13

,id,0,1,2,3,4,5,6,7,8,9
0,0,-0.616667,-0.716667,-0.783333,-0.800000,-1.283333,-1.283333,-1.383333,-1.333333,-1.350000,-1.350000
1,1,-0.616667,-0.716667,-0.783333,-0.800000,-1.283333,-1.283333,-1.383333,-1.333333,-1.350000,-1.600000
2,2,-0.616667,-0.716667,-0.783333,-0.800000,-1.283333,-1.283333,-1.383333,-1.316667,-1.716667,-1.316667
3,3,-0.616667,-0.716667,-0.783333,-0.800000,-1.283333,-1.283333,-1.383333,-1.333333,-1.700000,-1.666667
4,4,-0.616667,-0.716667,-0.783333,-0.800000,-1.283333,-1.283333,-1.383333,-1.750000,-1.333333,-1.316667
...,...,...,...,...,...,...,...,...,...,...,...
1019,1019,-1.050000,-2.000000,-2.016667,-2.050000,-2.050000,-2.083333,-2.883333,-1.233333,-2.750000,-2.716667
1020,1020,-1.050000,-1.983333,-2.016667,-2.033333,-2.050000,-2.083333,-2.883333,-2.816667,-1.216667,-1.216667
1021,1021,-1.050000,-2.000000,-2.016667,-2.050000,-2.050000,-2.083333,-2.883333,-2.816667,-1.216667,-2.716667
1022,1022,-1.050000,-2.000000,-2.016667,-2.050000,-2.050000,-2.083333,-2.883333,-2.816667,-2.816667,-1.183333
1023,1023,-1.050000,-1.983333,-2.016667,-2.033333,-2.050000,-2.083333,-2.883333,-2.816667,-2.800000,-2.750000

In [18]:
i = 0
id = 456

for tl_0 in list_tl:
    tl_1 = 50 - tl_0
    file_name = "reward_df_"+str(tl_0)+"_"+str(tl_1)+".csv"
    print("tl_0 = %s, tl_1 = %s" % (tl_0,tl_1))
    df_reward = pd.read_csv(file_name)
    tab_reward = [[] for _ in range(10)]
    for i in range(10):
        tab_reward[i] = df_reward[str(i)].values
    print(float(tab_reward[i][id]),float(tab_reward[i][id + 2**(9-i)]))

tl_0 = 10, tl_1 = 40
-3.5 -1.6166666666666667
tl_0 = 13, tl_1 = 37
-2.5 -1.6666666666666667
tl_0 = 15, tl_1 = 35
-2.45 -1.6666666666666667
tl_0 = 16, tl_1 = 34
-2.4 -1.6666666666666667
tl_0 = 19, tl_1 = 31
-2.316666666666667 -1.6833333333333331
tl_0 = 20, tl_1 = 30
-2.283333333333333 -1.6666666666666667
tl_0 = 22, tl_1 = 28
-2.216666666666667 -1.6666666666666667
tl_0 = 25, tl_1 = 25
-1.5 -1.6666666666666667
tl_0 = 28, tl_1 = 22
-1.45 -1.6666666666666667
tl_0 = 30, tl_1 = 20
-1.4166666666666667 -1.7166666666666666
tl_0 = 31, tl_1 = 19
-1.4 -1.7166666666666666
tl_0 = 34, tl_1 = 16
-1.35 -1.75
tl_0 = 35, tl_1 = 15
-1.3333333333333333 -1.75
tl_0 = 37, tl_1 = 13
-1.3166666666666669 -1.8
tl_0 = 40, tl_1 = 10
-1.2666666666666666 -2.6166666666666667

In [27]:
id = 428
s = id_to_strategy(id)
tl_0 = 10
for j in range(10):
    tl_0 += s[j]*3
tl_1 = 50 - tl_0
df_reward = pd.read_csv(file_name)
tab_reward = [[] for _ in range(10)]
for i in range(10):
    tab_reward[i] = df_reward[str(i)].values
    print(float(tab_reward[i][id]))

-0.6166666666666667
-2.0
-2.0166666666666666
-0.8166666666666667
-2.0166666666666666
-1.2
-2.0166666666666666
-2.7666666666666666
-1.2
-1.2

In [ ]:
file_name = "reward_df_convex.csv"
with open(file_name, "w") as f:
    f.write("id,0,1,2,3,4,5,6,7,8,9\n")
    for id in range(1024):

        s = id_to_strategy(id)
        tl_0 = 40
        for j in range(10):
            tl_0 -= s[j]*3
        tl_1 = 50 - tl_0
        df_reward = pd.read_csv("reward_df_"+str(tl_0)+"_"+str(tl_1)+".csv")

        text = str(id)
        tab_reward = [[] for _ in range(10)]
        for i in range(10):
            tab_reward[i] = df_reward[str(i)].values
            text = text + "," + str(float(tab_reward[i][id]))

        f.write(text+"\n")

In [ ]:
file_name = "reward_df_lessconvex.csv"
with open(file_name, "w") as f:
    f.write("id,0,1,2,3,4,5,6,7,8,9\n")
    for id in range(1024):

        s = id_to_strategy(id)
        num = 0
        for j in range(10):
            num += s[j]
        if num > 7:
            tl_1 = 25 + 5*(num-7)
        if num < 3:
            tl_1 = 10 + 5*num
        tl_0 = 50 - tl_1
        df_reward = pd.read_csv("reward_df_"+str(tl_0)+"_"+str(tl_1)+".csv")

        text = str(id)
        tab_reward = [[] for _ in range(10)]
        for i in range(10):
            tab_reward[i] = df_reward[str(i)].values
            text = text + "," + str(float(tab_reward[i][id]))

        f.write(text+"\n")

:

In [14]:
threshold = 2
file_name = "reward_df_50agents_sharpthreshold_smallestamplitude_%s.csv"%(threshold)

with open(file_name, "w") as f:
    f.write("id,0,1,2,3,4,5,6,7,8,9\n")
    for id in range(1024):

        s = id_to_strategy(id)
        n_1 = 0
        for j in range(10):
            n_1 += s[j]
        tl_1 = 20
        if n_1 >= threshold:
            tl_1 = 30
        tl_0 = 50 - tl_1
        df_reward = pd.read_csv("reward_df_50agents_"+str(tl_0)+"_"+str(tl_1)+".csv")

        text = str(id)
        tab_reward = [[] for _ in range(10)]
        for i in range(10):
            tab_reward[i] = df_reward[str(i)].values
            text = text + "," + str(float(tab_reward[i][id]))

        f.write(text+"\n")